### ISSUE TITLE
encoding issues in assertElementContains 

### ISSUE THREAD

**Issue by Grldk** [ssddanbrown/asserthtml#2]
We ran into encoding issues with assertElementContains:

```php
        $test = new HtmlTest('<p>Test \' & String</p>');

        $test->assertElementContains('p', 'Test \' & String');
```
This test fails, but it should succeed of course. A fix for this would be a change in this file:

https://github.com/ssddanbrown/asserthtml/blob/7971d6d442a27c607ca6cca4b219d08ae7fc9a78/src/Constraints/PageConstraint.php#L49

If you change ENT_QUOTES to ENT_NOQUOTES the test string is escaped correctly. Could PR this, but it might be a breaking change for people who relied on the previous behaviour? 

I'd say it's a bugfix, not a bc though.

**Comment by ssddanbrown** [comment]
Thanks for reporting @Grldk, Have addressed in 6baf3ef2087f5928ae34f0d41db27aefcdf60414.

Was actually a bit tricky due to the ampersand which is often expected to be html-encoded so gets auto-converted by the parsers involved, while the quoting done to match against escaped & non-escaped variations of the input would specifically handle quotes, resulting in a conflicting mix. 

I didn't want to alter the escaping logic since, as you say, some may depend on this (And this was taken from the original browserkit logic). I instead now also check the text string against the plain text content of the element, to work around html escaping completely.  There's still be some cases that this won't match against, I think that would require test every combination/variation of encoding to strictly do so, but this should cover most cases now which I'd consider good enough. 

Now published as a v2 breaking change since it does alter what's matched against.
